services:
    server:
        build:
            context: ./server
            target: dev
        container_name: antoine_exam_server
        environment:
            APP_ENV: development
        ports:
            - '9000:9000'
        volumes:
            - ./server:/app

    adminer:
        image: adminer:latest
        container_name: antoine_exam_adminer
        ports:
            - '8081:8080'
        environment:
            ADMINER_DEFAULT_SERVER: database
        networks:
            - front_network
            - backend_network

    mailhog:
        image: mailhog/mailhog
        container_name: antoine_exam_mailhog
        ports:
            - '8025:8025'
        networks:
            - front_network
