services:
    client:
        build:
            context: ./client
        container_name: antoine_exam_client
        ports:
            - '8080:80'
        networks:
            - front_network
        depends_on:
            - server
        volumes:
            - ./client:/var/www/html

    server:
        build:
            context: ./server
        container_name: antoine_exam_server
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        networks:
            - front_network
            - backend_network
        depends_on:
            - database
        volumes:
            - ./server:/app

    database:
        image: mysql:8.0
        container_name: antoine_exam_database
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - backend_network
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD || exit 1',
                ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    db_data:

networks:
    front_network:
    backend_network:
